import React from "react";
import Head from "next/head";
import Header from "../components/header";
import Hero from "../components/hero";
import Projects from "../components/projects";
import About from "../components/about";
import Footer from "../components/footer";

//Styles
import { Body } from "../components/body/Body.style";
import { Main } from "../components/main/Main.style";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bjornsen Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <Header />
        <Main>
          <Hero />
          <Projects />
          <About />
        </Main>
        <Footer />
      </Body>
    </>
  );
}
