import React from "react";
import Head from "next/head";
import Header from "../components/header";
import Hero from "../components/hero";
import Projects from "../components/projects";

//Styles
import { Body } from "../components/body/Body.style";
import { Main } from "../components/main/Main.style";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bjornsen Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <Header />
        <Main>
          <Hero id="home" />
          <Projects id="projects" />
        </Main>
        <footer></footer>
      </Body>
    </>
  );
}
